### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by meta-boy** [meta-boy/atheneum#4]
- [x] - Fix Jitters in the `TabBarView`
- [x] - add the `screen` for `Genre`
- [x] - sort in `reverse` order
- [x] - add  a way to toggle vertical or horizontal scrolling
- [ ] - good search interface
- [x] - Tap on image to hide the `AppBar`
- [ ] - Better UI, modern and fluid
- [ ] - Use even better code practices
- [ ] - add persistent storage to save preference
